/**
 * The Pi/OMP extension that a hook install writes into a runtime's extension directory.
 *
 * The extension is deliberately thin: it forwards the prompt to `skillful hook` on a child
 * process and injects whatever comes back. That keeps **one** implementation of the routing,
 * budget, cache and rendering logic — the CLI's — serving all four runtimes, instead of a
 * second one that would drift from the first.
 *
 * The generated source is TypeScript, as Pi's extension loader expects.
 *
 * Two properties matter more than anything else here:
 * - Every failure returns `{}`, which injects nothing. An extension that throws can break the
 *   host session, and no routing suggestion is worth that.
 * - The child process is killed on a timer, so a hung route cannot hang the agent.
 */

import type { CatalogRuntime } from "../../catalog/types.js";
import type { InstallContext } from "./types.js";

/** Budget for the child process. Slightly above the router's own budget so it can finish. */
const EXTENSION_TIMEOUT_MS = 2500;

/**
 * Build the extension source for one runtime.
 *
 * Values are embedded with `JSON.stringify` rather than string interpolation, so a path
 * containing a quote or a backslash cannot break out of the generated literal.
 */
export function extensionSource(ctx: InstallContext, runtime: CatalogRuntime): string {
  const executable = JSON.stringify(ctx.hookLauncher ?? ctx.nodeBin);
  const argumentPrefix = JSON.stringify(ctx.hookLauncher === undefined ? [ctx.cliEntry] : []);
  const runtimeName = JSON.stringify(runtime);

  return `/**
 * Skillful capability router — generated by \`skillful install\`. Do not edit by hand.
 *
 * This file is a thin forwarder. All routing, caching, budgeting and rendering live in the
 * Skillful CLI, so there is exactly one implementation of the decision across all runtimes.
 *
 * Remove it with \`skillful uninstall\`, which deletes this directory.
 */

import { spawn } from "node:child_process";

const EXECUTABLE = ${executable};
const ARGUMENT_PREFIX = ${argumentPrefix};
const RUNTIME = ${runtimeName};
const MARKER = "--managed-by-skillful";
const TIMEOUT_MS = ${EXTENSION_TIMEOUT_MS};

/**
 * Ask the CLI to route a prompt.
 *
 * Resolves to the raw stdout text, or null on any failure. It never rejects: a thrown error
 * from an event handler can disturb the host session, which is a far worse outcome than
 * injecting nothing.
 */
function routeViaCli(payload) {
  return new Promise((resolve) => {
    let child;
    try {
      child = spawn(EXECUTABLE, [...ARGUMENT_PREFIX, "hook", "--runtime", RUNTIME, MARKER], { stdio: ["pipe", "pipe", "ignore"] });
    } catch {
      resolve(null);
      return;
    }

    let out = "";
    let settled = false;
    const finish = (value) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve(value);
    };

    const timer = setTimeout(() => {
      try {
        child.kill();
      } catch {
        // The process may already be gone.
      }
      finish(null);
    }, TIMEOUT_MS);

    child.stdout.setEncoding("utf8");
    child.stdout.on("data", (chunk) => {
      out += chunk;
    });
    child.on("error", () => finish(null));
    child.on("close", () => finish(out));

    // A closed stdin must not surface as an unhandled error.
    child.stdin.on("error", () => {});
    try {
      child.stdin.end(JSON.stringify(payload));
    } catch {
      finish(null);
    }
  });
}

export default function (pi) {
  pi.on("before_agent_start", async (event, ctx) => {
    try {
      const prompt = typeof event?.prompt === "string" ? event.prompt : "";
      if (prompt.length === 0) return {};

      const raw = await routeViaCli({
        prompt,
        hook_event_name: "UserPromptSubmit",
        cwd: (ctx && typeof ctx.cwd === "string" && ctx.cwd) || process.cwd(),
        session_id: "",
      });
      if (typeof raw !== "string" || raw.length === 0) return {};

      const parsed = JSON.parse(raw);
      const text = parsed?.hookSpecificOutput?.additionalContext;
      if (typeof text !== "string" || text.length === 0) return {};

      return { message: { customType: "skillful", content: text, display: true } };
    } catch {
      return {};
    }
  });
}
`;
}
